title: Master Wifi Network Solution
email: myarachma92@gmail.com
description: >- # Deskripsi situs
  Master Wifi Network Solution adalah tempat solusi koneksi jaringan anda.
url: "https://masterwifinetworksolution.github.io"
baseurl: ""
markdown: kramdown
permalink: /:categories/:title/
paginate: 6
paginate_path: "/page/:num/"

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Muhammad Yusuf"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Muhammad Yusuf"
      comments: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-reading-time
  - jekyll-time-to-read

toc:
  min_level: 2
  max_level: 6
  no_toc_section_class: 'no_toc'
  list_class: 'toc-list'
  sublist_class: 'toc-sublist'
  item_class: 'toc-list-item'
  link_class: 'toc-link'
  heading_levels: [2, 3, 4, 5, 6]
  exclude_from_toc: []

assets:
  css: "/assets/css"

data_files:
  - files

data_documentation:
  - documentation
